### PR TITLE
GH #94: Strict argument extractors

### LINKED ISSUE #94: Strict argument extractors
Since Ninja v7.0.0, usage of `null` for controller method parameters is deprecated. Potential absence of request parameters in controller methods should be modeled with Java `Optional`s instead. Otherwise, the parameter is seen as required and a request omitting it, will be handled w/ a `BadRequestException` automatically, never invoking the controller method at all.

As this is a significant change in behavior, a feature toggle was introduced, namely `ninja.strict_argument_extractors` which is set to `false` per default (might change in the future).

This issue is about migration from the old deprecated behavior to the new one which means
- [ ] Replace all controller method parameters that can be potentially absent with Java `Optional`s
- [ ] Enable strict argument extractors by setting the before mentioned feature toggle to `true`

### PR DESCRIPTION
**Pull request by h-arlt**
Changes:
- enabled Ninja's strict argument extractors feature
- use Java Optionals for request parameters that are not required for precessing the request or that need custom validation error handling
- use method references to controller methods for route declarations instead of plain strings
- fixed minor issue in pagination

Closes #94

### CODE REVIEW

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java [hunk 1]
```diff
@@ -380,29 +379,30 @@ else if (action.equals("deleteDomain"))
      * @return overview of all white-listed domains
      */
     @FilterWith(WhitelistFilter.class)
-    public Result addDomain(Context context, @Param("domainName") String domainName)
+    public Result addDomain(Context context, @Param("domainName") Optional<String> domainName)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/AdminHandler.java:382]: Is `domainName` really optional? The UI always sends a value.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java [hunk 2]
```diff
@@ -416,9 +416,10 @@ public Result addDomain(Context context, @Param("domainName") String domainName)
      *            the context of this request
      * @return
      */
-    public Result showEmailStatistics(Context context, @Param("dayPage") int dayPage, @Param("weekPage") int weekPage,
-                                      @Param("sortDailyList") String sortDailyList,
-                                      @Param("sortWeeklyList") String sortWeeklyList)
+    public Result showEmailStatistics(Context context, @Param("dayPage") Optional<Integer> dayPage,
+                                      @Param("weekPage") Optional<Integer> weekPage,
+                                      @Param("sortDailyList") Optional<String> sortDailyList,
+                                      @Param("sortWeeklyList") Optional<String> sortWeeklyList)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/AdminHandler.java:422]: The now optional parameters are never used. The UI does not send them either. Remove them?

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java [hunk 3]
```diff
@@ -448,19 +449,26 @@ public Result showEmailStatistics(Context context, @Param("dayPage") int dayPage
...
     }
 
-    public Result getEmailSenderTablePage(Context context, @Param("scope") String scope, @Param("page") int page,
-                                          @Param("offset") int offset, @Param("limit") int limit,
-                                          @Param("sort") String sort, @Param("order") String order)
+    public Result getEmailSenderTablePage(Context context, @Param("scope") String scope,
+                                          @Param("page") Optional<Integer> page,
+                                          @Param("offset") Optional<Integer> offset,
+                                          @Param("limit") Optional<Integer> limit, @Param("sort") Optional<String> sort,
+                                          @Param("order") Optional<String> order)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/AdminHandler.java:456]: The parameter `page` is not used. Remove?

Are the remaining parameters really optional? The UI always sends a value for them.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java [hunk 4]
```diff
@@ -118,7 +119,7 @@ public Result listMails(@Param("mailboxAddress") @Email final String mailboxAddr
      * @return the details of the mail as a {@link MailData} object in JSON format
      */
     // @Get("/api/v1/mails/<mailId>")
-    public Result getMail(@PathParam("mailId") @DbId final Long mailId, @Attribute("userId") @DbId final Long userId,
+    public Result getMail(@PathParam("mailId") @DbId final Optional<Long> mailId, @Attribute("userId") @DbId final Long userId,
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:122]: The parameter `mailId` is not optional.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java [hunk 5]
```diff
@@ -170,7 +171,7 @@ public Result getMailAttachment(@PathParam("mailId") @DbId final Long mailId,
      * @return an empty result
      */
     // @Delete("/api/v1/mails/<mailId>")
-    public Result deleteMail(@PathParam("mailId") @DbId final Long mailId, @Attribute("userId") @DbId final Long userId,
+    public Result deleteMail(@PathParam("mailId") @DbId final Optional<Long> mailId, @Attribute("userId") @DbId final Long userId,
                              final Context context)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:175]: The parameter `mailId` is not optional.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java [hunk 6]
```diff
@@ -194,7 +195,7 @@ public Result deleteMail(@PathParam("mailId") @DbId final Long mailId, @Attribut
      *            the action that manipulates the mail entity and returns a corresponding result
      * @return the result produced by the action, or an error result
      */
-    private Result performAction(final Long mailId, final Long userId, final Context context,
+    private Result performAction(final Optional<Long> mailId, final Long userId, final Context context,
                                  final Function<Mail, Result> action)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:199]: The parameter `mailId` is not optional.

File: xcmailr-webapp/src/main/java/controllers/restapi/util/Email.java [hunk 7]
```diff
@@ -57,7 +56,7 @@ public EmailValidator(final Email dbIdAnnotation)
 
         public void validate(String value, String fieldName, Context context)
         {
-            String[] parts = StringUtils.split(StringUtils.defaultString(value), '@');
+            final String[] parts = HelperUtils.splitMailAddress(value);
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/controllers/restapi/util/Email.java:59]: `HelperUtils.splitMailAddress()` may return null so we would have to handle null in the condition that follows.

File: xcmailr-webapp/src/main/java/models/PageList.java [hunk 8]
```diff
@@ -119,7 +118,7 @@ public int getPageCount()
             return 1;
         }
 
-        int entrys = allEntrys.size();
+        int entrys = entries.size();
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/models/PageList.java:121]: Please rename `entrys` as well. Reading this hurts. ;-)

File: xcmailr-webapp/src/main/java/models/PageList.java [hunk 9]
```diff
@@ -119,7 +118,7 @@ public int getPageCount()
...
         if (entrys < pageSize)
```
Comment (jowerner) [inline xcmailr-webapp/src/main/java/models/PageList.java:122]: Small optimization:

```suggestion
        if (entrys <= pageSize)
```

**Review by jowerner — CHANGES_REQUESTED** [review]
Please have a look at my comments. We can discuss them later.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java [hunk 10]
```diff
@@ -167,20 +165,21 @@ public Result pagedMTX(Context context, @Param("p") int page)
      *            the time in days (all before will be deleted)
      * @return mail-transactions overview page
      */
-    public Result deleteMTXProcess(@PathParam("time") Integer time, Context context)
+    public Result deleteMTXProcess(@PathParam("time") Optional<Integer> time, Context context)
```
[the remark this answers is not in the document]
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:168]: Time is parsed as Integer and defaults to `null` in case it could not be parsed successfully. For this reason and since implementation does not require the parameter to be given, I made it optional.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java [hunk 11]
```diff
@@ -343,13 +342,13 @@ public Result callRemoveDomain(Context context, @Param("removeDomainsSelection")
      * @return overview of all white-listed domains
      */
     @FilterWith(WhitelistFilter.class)
-    public Result handleRemoveDomain(Context context, @Param("action") String action, @Param("domainId") long domainId)
+    public Result handleRemoveDomain(Context context, @Param("action") Optional<String> action,
+                                     @Param("domainId") Long domainId)
```
[the remark this answers is not in the document]
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:346]: Correct. But implementation does not require it. That's why I made it optional.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 1 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:382]: This is to allow custom error handling in case domainName is null or blank.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 2 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:422]: I made those parameters optional as sensible defaults can be used in case they are not given/valid. As pagination and sorting for statistics is currently not supported by UI but should be (or is planned to be at least).

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 3 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:456]: Sensible defaults can be used in case they are not given/valid. That's why I made them optional.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java [hunk 12]
```diff
@@ -149,7 +150,7 @@ public Result getMail(@PathParam("mailId") @DbId final Long mailId, @Attribute("
      * @return the attachment with the correct content type set
      */
     // @Get("/api/v1/mails/<mailId>/attachments/<attachmentName>")
-    public Result getMailAttachment(@PathParam("mailId") @DbId final Long mailId,
+    public Result getMailAttachment(@PathParam("mailId") @DbId final Optional<Long> mailId,
                                     @PathParam("attachmentName") @NotBlank final String attachmentName,
                                     @Attribute("userId") @DbId final Long userId, final Context context)
```
[the remark this answers is not in the document]
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:155]: Same as for `getMail`.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 5 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:175]: Same as for `getMail`.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 6 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java:199]: Please see my comment at `getMail`.

File: xcmailr-webapp/src/main/java/controllers/restapi/util/Email.java (hunk 7 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/util/Email.java:59]: Nice catch. Fixed.

File: xcmailr-webapp/src/main/java/models/PageList.java (hunk 8 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/models/PageList.java]: Done.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 3 above)
Comment (jowerner) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java:456]: All right, make sense. But please have another look at `page`, thx!

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java]: Reverted to non-optional.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 1 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java]: Reverted to non-optional parameter.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 2 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java]: Removed unused parameters.

File: xcmailr-webapp/src/main/java/controllers/AdminHandler.java (hunk 3 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/AdminHandler.java]: Removed `page` parameter.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 4 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java]: Reverted to non-optional parameter. However, this prevents us to perform custom error handling in case `mailId` is invalid (could not be parsed as Long)

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java]: Reverted to non-optional parameter.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 5 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java]: Reverted to non-optional parameter.

File: xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java (hunk 6 above)
Comment (h-arlt) [reply xcmailr-webapp/src/main/java/controllers/restapi/MailApiController.java]: Reverted to non-optional parameter.

**Review by jowerner — APPROVED** [review]
